### ISSUE TITLE
Keyboard Double Arrow icons are missing

### ISSUE THREAD

**Issue by jagabomb** [EOS-uiux-Solutions/eos-icons-react#27]
Hi there,

I am trying to use the following icon from EOS icons:
[keyboard_double_arrow_left](https://eos-icons.com/?iconName=keyboard_double_arrow_left&type=static)
From what I can see, it seems like this icon is not available with this react library.

**Comment by cyntss** [comment]
I reviewed on storybook and only the double arrow pointing to the right is available:

https://storybook.eos-icons.com/?path=/story/icon-eos-double-arrow--default

**Comment by cyntss** [comment]
@jagabomb I just merged https://github.com/EOS-uiux-Solutions/eos-icons-react/pull/20 which is updating this package to the latest eos-icons, so this should fix the issue

**Comment by jagabomb** [comment]
@cyntss Thanks for the update. I will test it out and let you know if it resolved the issue.

**Comment by jagabomb** [comment]
@cyntss The icon is now available in the library. Thanks!
